# built referencing https://www.home-assistant.io/installation/linux#install-home-assistant-core

- name: Install required packages
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - vim
          - python3
          - python3-dev
          - python3-venv
          - python3-pip
          - bluez
          - libffi-dev
          - libssl-dev
          - libjpeg-dev
          - zlib1g-dev
          - autoconf
          - build-essential
          - libopenjp2-7
          - libtiff6
          - libturbojpeg0-dev
          - tzdata
          - python3-full
          - python3-pip
          - python3-virtualenv
          - acl
          - plocate
        state: present

    - name: Create homeassistant user
      user:
        name: homeassistant
        state: present
        shell: /bin/bash
        system: yes
        createhome: yes

    - name: Create directory
      file:
        path: /srv/homeassistant
        state: directory
        owner: homeassistant
        group: homeassistant
        mode: '0770'

    - name: Create virtual environment at /srv/homeassistant
      pip:
        name: virtualenv
        virtualenv: /srv/homeassistant
        state: present
      become: true
      become_user: homeassistant

    - name: Install homeassistant and wheel in virtual environment
      pip:
        name:
          - homeassistant==2023.4.6
          - wheel
        virtualenv: /srv/homeassistant
        state: present
      become: true
      become_user: homeassistant


# TODO:
# create auto start script
# add to cron
